using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace faturamento_api.Migrations
{
    /// <inheritdoc />
    public partial class AlterNumeroNotaFiscalAutoIncrement : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Numero",
                table: "NotasFiscais");

            migrationBuilder.AddColumn<int>(
                name: "Numero",
                table: "NotasFiscais",
                type: "integer",
                nullable: true);

            migrationBuilder.Sql("""
                WITH notas_numeradas AS (
                    SELECT "Id", ROW_NUMBER() OVER (ORDER BY "Id")::integer AS "NovoNumero"
                    FROM "NotasFiscais"
                )
                UPDATE "NotasFiscais" AS nota
                SET "Numero" = notas_numeradas."NovoNumero"
                FROM notas_numeradas
                WHERE nota."Id" = notas_numeradas."Id";
                """);

            migrationBuilder.AlterColumn<int>(
                name: "Numero",
                table: "NotasFiscais",
                type: "integer",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.Sql("""
                ALTER TABLE "NotasFiscais"
                ALTER COLUMN "Numero" ADD GENERATED BY DEFAULT AS IDENTITY;
                """);

            migrationBuilder.Sql("""
                SELECT setval(
                    pg_get_serial_sequence('"NotasFiscais"', 'Numero'),
                    COALESCE((SELECT MAX("Numero") FROM "NotasFiscais"), 1),
                    (SELECT MAX("Numero") FROM "NotasFiscais") IS NOT NULL
                );
                """);

            migrationBuilder.CreateIndex(
                name: "IX_NotasFiscais_Numero",
                table: "NotasFiscais",
                column: "Numero",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_NotasFiscais_Numero",
                table: "NotasFiscais");

            migrationBuilder.DropColumn(
                name: "Numero",
                table: "NotasFiscais");

            migrationBuilder.AddColumn<string>(
                name: "Numero",
                table: "NotasFiscais",
                type: "text",
                nullable: false,
                defaultValue: "");
        }
    }
}
