services:
  estoque-api:
    build:
      context: ./api
      dockerfile: estoque-api/Dockerfile
    container_name: estoque-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=estoque_db;Username=postgres;Password=postgres"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  faturamento-api:
    build:
      context: ./api
      dockerfile: faturamento-api/Dockerfile
    container_name: faturamento-api
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=faturamento_db;Username=postgres;Password=postgres"
      EstoqueApi__BaseUrl: "http://estoque-api:8080/"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      estoque-api:
        condition: service_started

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
  postgres-data:
    name: korp-postgres-data
    driver: local
